

import numpy as np 
import matplotlib.pyplot as plt
import os
import shutil
import sys
#We will improve this code so we create a 


#Crearemos un script que cree el archivo necesario 

Tau=float(sys.argv[1]) 
mu=float(sys.argv[2])
PBB=float(sys.argv[3])
Nsim=int(sys.argv[4])

Lx=float(sys.argv[5])
Ly=float(sys.argv[6])
steps=int(sys.argv[7])
Mc_steps=int(sys.argv[8])
Box=[-1*Lx,Lx,-1*Ly,Ly,-0.3,0.3 ]



# Box=[-25.0,25.0,-25.0,25.0 , -0.3,0.3]
Nsim_ini=20
Nsim_fin=21
Taus=[ 1e4]
mus=[4.8]
PBBs=[1.0]


def Input_file(Parent_dir,steps,Tau,mu,PBB,Box,Config_dir,Nsim,Mc_steps):
    seed=100+Nsim*10
    Input_dir=Parent_dir+'/Inputs_MC/'
    Reaction_dir=Parent_dir+'Reactions/'
    Dump_dir=Parent_dir+'Dump_Pol/'
    Results_dir=Parent_dir+'Results/'

    
    os.makedirs(Input_dir,exist_ok=True)
    os.makedirs(Reaction_dir,exist_ok=True)
    os.makedirs(Dump_dir,exist_ok=True)
    os.makedirs(Results_dir,exist_ok=True)

    f = open(Input_dir+'in.MC_Filament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}'.format(Tau,mu,PBB,Box[1],Box[3],Nsim), 'w')
    f.write('log            '+Results_dir+'/MC_Log_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat \n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('units          lj\n')
    f.write('dimension      2\n')
    f.write('atom_style     molecular')
    f.write('\n')
    f.write('read_data      {} extra/bond/per/atom 5  extra/special/per/atom 20  extra/angle/per/atom 3\n'.format(Config_dir))
    f.write('\n')
    f.write('fix            Twodim all enforce2d\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskGMonomers atom "type==4"\n')
    f.write('group          GMonomers dynamic all  var vMaskGMonomers  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskTails atom "type==3"\n')
    f.write('group          Tails dynamic all  var vMaskTails  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskHeads atom "type==1"\n')
    f.write('group          Heads dynamic all  var vMaskHeads  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskFilamentBulk atom "type==2"\n')
    f.write('group          FilamentBulk dynamic all  var vMaskFilamentBulk  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskPolymerisation0Group atom "type==4"\n')
    f.write('group          Polymerisation0Group dynamic all  var vMaskPolymerisation0Group  every 4 \n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskPolymerisation1Group atom "type==4 || type==1"\n')
    f.write('group          Polymerisation1Group dynamic all  var vMaskPolymerisation1Group  every 4 \n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskDepolymerisation0Group atom "type==2 || type==3"\n')
    f.write('group          Depolymerisation0Group dynamic all  var vMaskDepolymerisation0Group  every 4 \n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskDepolymerisation3Group atom "type==1 || type==3" \n')
    f.write('group          Depolymerisation3Group dynamic all  var vMaskDepolymerisation3Group  every 4\n')
    f.write('\n')
    f.write('\n')
    f.write('neighbor       3.0 bin\n')
    f.write('neigh_modify   every 4 delay 0\n')
    f.write('comm_modify    cutoff 10\n')
    f.write('\n')
    f.write('\n')
    f.write('special_bonds  lj 1.0 1.0 1.0\n')
    f.write('bond_style     harmonic\n')
    f.write('bond_coeff     1 500 1.0\n')
    f.write('\n')
    f.write('\n')
    f.write('angle_style    harmonic\n')
    f.write('angle_coeff    * 500.0 180.0\n')
    f.write('\n')
    f.write('\n')
    f.write('pair_style     hybrid/overlay  cosine/squared 1.00  zero 1.50\n')
    f.write('pair_coeff     * * cosine/squared 10.0 1.00 1.00 wca\n')
    f.write('pair_coeff     2 3 zero 1.50\n')
    f.write('pair_coeff     1 3 zero 1.50\n')
    f.write('\n')
    f.write('\n')
    f.write('fix            fGCMCext GMonomers gcmc 5 75 0  4 {} 1.0 {} 1.0  group Polymerisation0Group group Polymerisation1Group\n'.format(seed,mu))
    f.write('run            {}\n'.format(Mc_steps))
    f.write('\n')
    f.write('\n')
    f.write('molecule       mPrePolymerisation1 '+Reaction_dir+ 'Pre_Polymerisation1.txt\n')
    f.write('molecule       mPostPolymerisation1 '+Reaction_dir+ 'Post_Polymerisation1.txt\n')
    f.write('molecule       mPrePolymerisation2 '+Reaction_dir+ 'Pre_Polymerisation2.txt\n')
    f.write('molecule       mPostPolymerisation2 '+Reaction_dir+ 'Post_Polymerisation2.txt\n')
    f.write('molecule       mPrePolymerisation3 '+Reaction_dir+ 'Pre_Polymerisation3.txt\n')
    f.write('molecule       mPostPolymerisation3 '+Reaction_dir+ 'Post_Polymerisation3.txt\n')
    f.write('molecule       mPreDepolymerisation0 '+Reaction_dir+ 'Pre_Depolymerisation0.txt\n')
    f.write('molecule       mPostDepolymerisation0 '+Reaction_dir+ 'Post_Depolymerisation0.txt\n')
    f.write('molecule       mPreDepolymerisation1 '+Reaction_dir+ 'Pre_Depolymerisation1.txt\n')
    f.write('molecule       mPostDepolymerisation1 '+Reaction_dir+ 'Post_Depolymerisation1.txt\n')
    f.write('molecule       mPreDepolymerisation2 '+Reaction_dir+ 'Pre_Depolymerisation2.txt\n')
    f.write('molecule       mPostDepolymerisation2 '+Reaction_dir+ 'Post_Depolymerisation2.txt\n')
    f.write('molecule       mPreDepolymerisation3 '+Reaction_dir+ 'Pre_Depolymerisation3.txt\n')
    f.write('molecule       mPostDepolymerisation3 '+Reaction_dir+ 'Post_Depolymerisation3.txt\n')
    f.write('\n')
    f.write('\n')
    f.write('fix                 freact all bond/react  stabilization yes AllAtoms 0.1  reset_mol_ids no         &\nreact Polymerisation0 Polymerisation0Group 10 0.900000 1.00000 mPostDepolymerisation3 mPreDepolymerisation3 '+Reaction_dir+'Map_Polymerisation0.txt  prob 0.00010 {} stabilize_steps 9  &\nreact Polymerisation1 Polymerisation1Group 10 0.900000 1.100000 mPrePolymerisation1 mPostPolymerisation1 '.format(seed)+Reaction_dir+'Map_Polymerisation1.txt  prob {} {} stabilize_steps 9         &\nreact Polymerisation2 Polymerisation1Group 10 0.900000 1.100000 mPrePolymerisation2 mPostPolymerisation2 '.format(PBB,seed)+Reaction_dir+'Map_Polymerisation2.txt  prob {} {} stabilize_steps 9 &\nreact Polymerisation3 Polymerisation1Group 10 0.900000 1.100000 mPrePolymerisation3 mPostPolymerisation3 '.format(PBB,seed)+Reaction_dir+'Map_Polymerisation3.txt  prob {} {} stabilize_steps 9     &\nreact Depolymerisation0 Depolymerisation0Group 10 0.90000 1.100000 mPreDepolymerisation0 mPostDepolymerisation0 '.format(PBB,seed)+Reaction_dir+'Map_Depolymerisation0.txt  prob 1.000 {} molecule intra stabilize_steps 9    &\nreact Depolymerisation1 Depolymerisation0Group 10 0.90000 1.100000 mPreDepolymerisation1 mPostDepolymerisation1 '.format(seed)+Reaction_dir+'Map_Depolymerisation1.txt  prob 1.00000 {} molecule intra stabilize_steps 9     &\nreact Depolymerisation2 Depolymerisation0Group 10 0.90000 1.100000 mPreDepolymerisation2 mPostDepolymerisation2 '.format(seed)+Reaction_dir+'Map_Depolymerisation2.txt  prob 1.000000 {} molecule intra stabilize_steps 9     &\nreact Depolymerisation3 Depolymerisation3Group 10 0.90000 1.100000 mPreDepolymerisation3 mPostDepolymerisation3 '.format(seed)+Reaction_dir+'Map_Depolymerisation3.txt  prob 1.000000 {} molecule intra stabilize_steps 9\n'.format(seed))
    f.write('\n')
    f.write('\n')
    f.write('fix        fLang all langevin 1.0 1.0 1.0 {}\n'.format(seed))
    f.write('fix        fNVE AllAtoms_REACT nve\n')
    f.write('\n')
    f.write('\n')
    f.write('variable   vMCMASK equal (step<{})*-1000.0\n'.format(Mc_steps))
    
    f.write('variable   vNewTailsTime atom "v_vMCMASK+f_fTailsTime + gmask(bond_react_MASTER_group) * gmask(GMonomers)*(-f_fTailsTime+step ) "\n')
    f.write('fix        fTailsTime all store/state 10 v_vNewTailsTime\n')
    f.write('variable   vTailsTime atom (step-f_fTailsTime)/{}\n'.format(Tau))
    f.write('variable   vTailsP atom 1.0-exp(-v_vTailsTime)\n')
    f.write('\n')
    f.write('\n')

    if(Nsim==1):
        f.write('dump       2 all custom 25 '+Dump_dir+'MC_Filament_Full_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.xyz id mol type x y z v_vTailsTime v_vTailsP\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('dump       1 DumpGroup custom 25 '+Dump_dir+'MC_Filament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.xyz id mol type x y z v_vTailsTime v_vNewTailsTime v_vTailsTime\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))

    f.write('\n')
    f.write('\n')

    f.write('variable           vNumall equal count(all)\n')
    f.write('compute            ctempall all temp\n')
    f.write('compute_modify     ctempall dynamic/dof yes\n')
    f.write('compute            ctempGMonomers GMonomers temp\n')
    f.write('compute_modify     ctempGMonomers dynamic/dof yes\n')


    f.write('variable           vNumGMonomers equal count(GMonomers)\n')
    f.write('compute            ctempTails Tails temp\n')
    f.write('compute_modify     ctempTails dynamic/dof yes\n')
    f.write('variable           vNumTails equal count(Tails)\n')
    f.write('compute            ctempHeads Heads temp\n')
    f.write('compute_modify     ctempHeads dynamic/dof yes\n')
    f.write('variable           vNumHeads equal count(Heads)\n')
    f.write('compute            ctempFilamentBulk FilamentBulk temp\n')
    f.write('compute_modify     ctempFilamentBulk dynamic/dof yes\n')

    f.write('variable           vNumFilamentBulk equal count(FilamentBulk)\n')
    f.write('thermo             10\n')
    f.write('compute_modify     thermo_temp dynamic/dof yes\n')
    f.write('\n')
    f.write('\n')
    f.write('variable           TPol equal         "f_fTPol+(v_vNumFilamentBulk>0)"\n')
    f.write('fix                fTPol all ave/time 1 1 1 v_TPol\n')
    f.write('\n')
    f.write('\n')
    

    f.write('fix                fStatsThermo all ave/time 1000 1 1000  v_vNumall c_ctempall  v_vNumGMonomers c_ctempGMonomers  v_vNumTails c_ctempTails  v_vNumHeads c_ctempHeads  v_vNumFilamentBulk c_ctempFilamentBulk  file '+Parent_dir+'Results/MC_StatsThermo_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('\n')
    f.write('\n')
    f.write('fix                 fStatsRxn all ave/time 1000 1 1000  f_fGCMCext[3] f_fGCMCext[4] f_fGCMCext[5] f_fGCMCext[6]  f_freact[*]  file '+Parent_dir+'Results/StatsRxn_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))

    f.write('compute            cBonds DumpGroup property/local batom1 batom2 btype\n')
    f.write('compute            cBondsDet DumpGroup bond/local dist engpot\n')
    f.write('dump               dBonds DumpGroup local 25 '+Parent_dir+'Dump_Pol/MC_Filament_Bonds_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat index c_cBonds[1] c_cBonds[2] c_cBonds[3] c_cBondsDet[1] c_cBondsDet[2]\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('# compute             cAngles all property/local aatom1 aatom2 aatom3 atype\n')
    f.write('# dump                dAngles all local 100 '+Parent_dir+'Results/Angles_OneFilament_Tau_{}_mu_{}_Lx_{}_Ly_{}_Nsim_{}.dat.dat index c_cAngles[1] c_cAngles[2] c_cAngles[3] c_cAngles[4]\n'.format(Tau,mu,Box[1],Box[3],Nsim))
    
    
    f.write('\n')
    f.write('\n')

    f.write('timestep               0.002\n')
    f.write('run                    {}\n'.format(steps))
    
    f.close()

    return 


def Input_file_OneFilament(Parent_dir,steps,Tau,mu,PBB,Box,Config_dir,Nsim,Mc_steps):
    seed=100+Nsim*10
    Input_dir=Parent_dir+'Inputs_MC/'
    Reaction_dir=Parent_dir+'Reactions/'
    Dump_dir=Parent_dir+'Dump_Pol/'
    Result_dir=Parent_dir+'Results/'
    os.makedirs(Input_dir,exist_ok=True)
    os.makedirs(Reaction_dir,exist_ok=True)
    os.makedirs(Dump_dir,exist_ok=True)
    os.makedirs(Result_dir,exist_ok=True)
    f = open(Input_dir+'in.MC_OneFilament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}'.format(Tau,mu,PBB,Box[1],Box[3],Nsim), 'w')
    f.write('log            '+Parent_dir+'Results/MC_OneFilament_Log_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('units          lj\n')
    f.write('dimension      2\n')
    f.write('atom_style     molecular')
    f.write('\n')
    f.write('read_data      {} extra/bond/per/atom 5  extra/special/per/atom 20  extra/angle/per/atom 3\n'.format(Config_dir))
    f.write('\n')
    f.write('fix            Twodim all enforce2d\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskGMonomers atom "type==4"\n')
    f.write('group          GMonomers dynamic all  var vMaskGMonomers  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskTails atom "type==3"\n')
    f.write('group          Tails dynamic all  var vMaskTails  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskHeads atom "type==1"\n')
    f.write('group          Heads dynamic all  var vMaskHeads  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskFilamentBulk atom "type==2"\n')
    f.write('group          FilamentBulk dynamic all  var vMaskFilamentBulk  every 1\n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskPolymerisation0Group atom "type==4"\n')
    f.write('group          Polymerisation0Group dynamic all  var vMaskPolymerisation0Group  every 4 \n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskPolymerisation1Group atom "type==4 || type==1"\n')
    f.write('group          Polymerisation1Group dynamic all  var vMaskPolymerisation1Group  every 4 \n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskDumpGroup atom "type==3 || type==1 || type==2"\n')
    f.write('group          DumpGroup dynamic all  var vMaskDumpGroup  every 10 \n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskDepolymerisation0Group atom "type==2 || type==3"\n')
    f.write('group          Depolymerisation0Group dynamic all  var vMaskDepolymerisation0Group  every 4 \n')
    f.write('\n')
    f.write('\n')
    f.write('variable       vMaskDepolymerisation3Group atom "type==1 || type==3" \n')
    f.write('group          Depolymerisation3Group dynamic all  var vMaskDepolymerisation3Group  every 4\n')
    f.write('\n')
    f.write('\n')
    f.write('neighbor       3.0 bin\n')
    f.write('neigh_modify   every 4 delay 0\n')
    f.write('comm_modify    cutoff 10\n')
    f.write('\n')
    f.write('\n')
    f.write('special_bonds  lj 1.0 1.0 1.0\n')
    f.write('bond_style     harmonic\n')
    f.write('bond_coeff     1 500.0 1.0\n')
    f.write('\n')
    f.write('\n')
    f.write('angle_style    harmonic\n')
    f.write('angle_coeff    * 500.0 180.0\n')
    f.write('\n')
    f.write('\n')
    f.write('pair_style     hybrid/overlay  cosine/squared 1.00  zero 1.50\n')
    f.write('pair_coeff     * * cosine/squared 10.0 1.00 1.00 wca\n')
    f.write('pair_coeff     2 3 zero 1.50\n')
    f.write('pair_coeff     1 3 zero 1.50\n')
    f.write('\n')
    f.write('\n')
    f.write('fix            fGCMCext GMonomers gcmc 5 75 0  4  {}  1.0 {} 1.0  group Polymerisation0Group group Polymerisation1Group\n'.format(seed,mu))
    f.write('run            {}\n'.format(Mc_steps))
    f.write('\n')
    f.write('\n')
    f.write('molecule       mPrePolymerisation1 '+Reaction_dir+ 'Pre_Polymerisation1.txt\n')
    f.write('molecule       mPostPolymerisation1 '+Reaction_dir+ 'Post_Polymerisation1.txt\n')
    f.write('molecule       mPrePolymerisation2 '+Reaction_dir+ 'Pre_Polymerisation2.txt\n')
    f.write('molecule       mPostPolymerisation2 '+Reaction_dir+ 'Post_Polymerisation2.txt\n')
    f.write('molecule       mPrePolymerisation3 '+Reaction_dir+ 'Pre_Polymerisation3.txt\n')
    f.write('molecule       mPostPolymerisation3 '+Reaction_dir+ 'Post_Polymerisation3.txt\n')
    f.write('molecule       mPreDepolymerisation0 '+Reaction_dir+ 'Pre_Depolymerisation0.txt\n')
    f.write('molecule       mPostDepolymerisation0 '+Reaction_dir+ 'Post_Depolymerisation0.txt\n')
    f.write('molecule       mPreDepolymerisation1 '+Reaction_dir+ 'Pre_Depolymerisation1.txt\n')
    f.write('molecule       mPostDepolymerisation1 '+Reaction_dir+ 'Post_Depolymerisation1.txt\n')
    f.write('molecule       mPreDepolymerisation2 '+Reaction_dir+ 'Pre_Depolymerisation2.txt\n')
    f.write('molecule       mPostDepolymerisation2 '+Reaction_dir+ 'Post_Depolymerisation2.txt\n')
    f.write('molecule       mPreDepolymerisation3 '+Reaction_dir+ 'Pre_Depolymerisation3.txt\n')
    f.write('molecule       mPostDepolymerisation3 '+Reaction_dir+ 'Post_Depolymerisation3.txt\n')
    f.write('\n')
    f.write('\n')
    f.write('fix                 freact all bond/react  stabilization yes AllAtoms 0.1  reset_mol_ids no         &\nreact Polymerisation1 Polymerisation1Group 10 0.900000 1.100000 mPrePolymerisation1 mPostPolymerisation1 '+Reaction_dir+'Map_Polymerisation1.txt  prob {} {} stabilize_steps 9         &\nreact Polymerisation2 Polymerisation1Group 10 0.900000 1.100000 mPrePolymerisation2 mPostPolymerisation2 '.format(PBB,seed)+Reaction_dir+'Map_Polymerisation2.txt  prob {} {} stabilize_steps 9 &\nreact Polymerisation3 Polymerisation1Group 10 0.900000 1.100000 mPrePolymerisation3 mPostPolymerisation3 '.format(PBB,seed)+Reaction_dir+'Map_Polymerisation3.txt  prob {} {} stabilize_steps 9     &\nreact Depolymerisation0 Depolymerisation0Group 10 0.90000 1.100000 mPreDepolymerisation0 mPostDepolymerisation0 '.format(PBB,seed)+Reaction_dir+'Map_Depolymerisation0.txt  prob 1.0 {} stabilize_steps 9    &\nreact Depolymerisation1 Depolymerisation0Group 10 0.90000 1.100000 mPreDepolymerisation1 mPostDepolymerisation1 '.format(seed)+Reaction_dir+'Map_Depolymerisation1.txt  prob 1.0 {} stabilize_steps 9     &\nreact Depolymerisation2 Depolymerisation0Group 10 0.90000 1.100000 mPreDepolymerisation2 mPostDepolymerisation2 '.format(seed)+Reaction_dir+'Map_Depolymerisation2.txt  prob 1.0 {} stabilize_steps 9  \n'.format(seed))
    f.write('\n')
    f.write('\n')
    f.write('fix        fLang all langevin 1.0 1.0 1.0 {}\n'.format(seed))
    f.write('fix        fNVE AllAtoms_REACT nve\n')
    f.write('\n')
    f.write('\n')
    f.write('variable   vMCMASK equal (step<{})*-1000.0\n'.format(Mc_steps))
    f.write('variable   vNewTailsTime atom "v_vMCMASK+f_fTailsTime + gmask(bond_react_MASTER_group) * gmask(GMonomers)*(-f_fTailsTime+step ) "\n')
    f.write('fix        fTailsTime all store/state 10 v_vNewTailsTime\n')
    f.write('variable   vTailsTime atom (step-f_fTailsTime)/{}\n'.format(Tau))
    f.write('variable   vTailsP atom 1.0-exp(-v_vTailsTime)\n')
    f.write('\n')
    f.write('\n')

    if(Nsim==1):
        f.write('dump       2 all custom 25 '+Parent_dir+'Dump_Pol/MC_OneFilament_Full_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.xyz id mol type x y z v_vTailsTime v_vNewTailsTime v_vTailsTime\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))

    f.write('dump       1 DumpGroup custom 25 '+Parent_dir+'Dump_Pol/MC_OneFilament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.xyz id mol type x y z v_vTailsTime v_vNewTailsTime v_vTailsTime\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('\n')
    f.write('\n')

    f.write('variable           vNumall equal count(all)\n')
    f.write('compute            ctempall all temp\n')
    f.write('compute_modify     ctempall dynamic/dof yes\n')
    f.write('compute            ctempGMonomers GMonomers temp\n')
    f.write('compute_modify     ctempGMonomers dynamic/dof yes\n')


    f.write('variable           vNumGMonomers equal count(GMonomers)\n')
    f.write('compute            ctempTails Tails temp\n')
    f.write('compute_modify     ctempTails dynamic/dof yes\n')
    f.write('variable           vNumTails equal count(Tails)\n')
    f.write('compute            ctempHeads Heads temp\n')
    f.write('compute_modify     ctempHeads dynamic/dof yes\n')
    f.write('variable           vNumHeads equal count(Heads)\n')
    f.write('compute            ctempFilamentBulk FilamentBulk temp\n')
    f.write('compute_modify     ctempFilamentBulk dynamic/dof yes\n')

    f.write('variable           vNumFilamentBulk equal count(FilamentBulk)\n')
    f.write('thermo             10\n')
    f.write('compute_modify     thermo_temp dynamic/dof yes\n')
    f.write('\n')
    f.write('\n')
    f.write('variable           TPol equal         "f_fTPol+(v_vNumFilamentBulk>0)"\n')
    f.write('fix                fTPol all ave/time 1 1 1 v_TPol\n')
    f.write('\n')
    f.write('\n')
    f.write('fix                fStatsThermo all ave/time 1000 1 1000  v_vNumall c_ctempall  v_vNumGMonomers c_ctempGMonomers  v_vNumTails c_ctempTails  v_vNumHeads c_ctempHeads  v_vNumFilamentBulk c_ctempFilamentBulk file '+Parent_dir+'Results/MC_StatsThermo_OneFilament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('\n')
    f.write('\n')
    f.write('fix                 fStatsRxn all ave/time 1000 1 1000  f_fGCMCext[3] f_fGCMCext[4] f_fGCMCext[5] f_fGCMCext[6]  f_freact[*] f_fTPol  file '+Parent_dir+'Results/StatsRxn_OneFilament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))

    f.write('compute            cBonds DumpGroup property/local batom1 batom2 btype\n')
    f.write('compute            cBondsDet DumpGroup bond/local dist engpot\n')
    f.write('dump               dBonds DumpGroup local 25 '+Parent_dir+'Dump_Pol/MC_Filament_Bonds_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat index c_cBonds[1] c_cBonds[2] c_cBonds[3] c_cBondsDet[1] c_cBondsDet[2]\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))
    f.write('# compute             cAngles all property/local aatom1 aatom2 aatom3 atype\n')
    f.write('# dump                dAngles all local 100 Results/Angles_OneFilament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}.dat.dat index c_cAngles[1] c_cAngles[2] c_cAngles[3] c_cAngles[4]\n'.format(Tau,mu,PBB,Box[1],Box[3],Nsim))

    f.write('\n')
    f.write('\n')

    f.write('timestep               0.002\n')
    f.write('run                    {}\n'.format(steps))
    #I HAD 1E6 steps 
    
    f.close()

    return 


def Config_file(Parent_dir,Tau,mu,PBB,Box, Nsim, Angle_types,Atom_types,Bond_types):

    
    Config_dir=Parent_dir+'Config_MC/'
    os.makedirs(Config_dir,exist_ok=True)
    Config_dir=Config_dir+'MC_Filament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}_config.txt'.format(Tau,mu,PBB,Box[1],Box[3],Nsim)
    #The first part is easy.. you first create de configuration file
    f = open(Config_dir, 'w')
    f.write('First line of this test\n')
    f.write('{} atoms\n'.format(0) )
    f.write('{} bonds\n'.format(0))
    f.write('{} angles\n'.format(0))
    f.write('{} atom types\n'.format(Atom_types))
    f.write('{} bond types\n'.format(Bond_types))
    f.write('{} angle types\n'.format(Angle_types))
    f.write('{} {} xlo xhi\n'.format(Box[0],Box[1]))
    f.write('{} {} ylo yhi\n'.format(Box[2],Box[3]))
    f.write('{} {} zlo zhi\n'.format(Box[4],Box[5]))

    #With this the header ends and we start with the more problematic part
    #You need to understand the order 
    #FOr atoms is   id mol type x y z
    f.write('\n')
    f.write('Masses\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 1\n')
    f.write('3 1\n')
    f.write('4 1\n')        
    f.close()

    return Config_dir


def Config_file_OneFilament(Parent_dir,Tau,mu,PBB,Box, Nsim, Angle_types,Atom_types,Bond_types):
    Config_dir=Parent_dir+'Config_MC/'
    os.makedirs(Config_dir,exist_ok=True)
    Config_dir+='MC_OneFilament_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}_config.txt'.format(Tau,mu,PBB,Box[1],Box[3],Nsim)
    
    #The first part is easy.. you first create de configuration file
    f = open(Config_dir, 'w')
    f.write('First line of this test\n')
    f.write('{} atoms\n'.format(2) )
    f.write('{} bonds\n'.format(1))
    f.write('{} angles\n'.format(0))
    f.write('{} atom types\n'.format(Atom_types))
    f.write('{} bond types\n'.format(Bond_types))
    f.write('{} angle types\n'.format(Angle_types))
    f.write('{} {} xlo xhi\n'.format(Box[0],Box[1]))
    f.write('{} {} ylo yhi\n'.format(Box[2],Box[3]))
    f.write('{} {} zlo zhi\n'.format(Box[4],Box[5]))

    #With this the header ends and we start with the more problematic part
    #You need to understand the order 
    #FOr atoms is   id mol type x y z
    f.write('\n')
    f.write('Masses\n')
    f.write('\n')
    
    f.write('1 1\n')
    f.write('2 1\n')
    f.write('3 1\n')
    f.write('4 1\n')
    f.write('\n')
    f.write('\n')
    
    f.write('Atoms\n')
    f.write('\n')
    f.write('1 1 1 0.0 1.0 0.0\n')
    f.write('2 1 3 0.0 0.0 0.0\n')
    f.write('\n')
    f.write('\n')
    
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 1 2\n')
    

    f.close()




    return Config_dir




def Reactions(Parent_dir,Nsim):
    Reaction_dir=Parent_dir+'Reactions/'
    os.makedirs(Reaction_dir,exist_ok=True)
    seed=100+Nsim*10
    f=open(Reaction_dir+'Map_Depolymerisation0.txt','w')
    f.write('#Depolimerisation0 LongFil\n')
    f.write('\n')
    f.write('4 equivalences\n')
    f.write('1 edgeIDs\n')
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('EdgeIDs\n')
    f.write('\n')
    f.write('4\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('4 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('custom "(1.0-exp(-rxndiffIvan(v_vTailsTime,1))) > random(0.0,1.0,{})"\n'.format(float(seed)))
    f.write('\n')
    f.close()


    f=open(Reaction_dir+'Map_Depolymerisation1.txt','w')
    f.write('#Depolimerisation1 4-mer\n')
    f.write('\n')
    f.write('4 equivalences\n')
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('4 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('custom "(1.0-exp(-rxndiffIvan(v_vTailsTime,1))) > random(0.0,1.0,{})"\n'.format(float(seed)))
    f.write('\n')
    f.close()

    f=open(Reaction_dir+'Map_Depolymerisation1.txt','w')
    f.write('#Depolimerisation1 4-mer\n')
    f.write('\n')
    f.write('4 equivalences\n')
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('4 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('custom "(1.0-exp(-rxndiffIvan(v_vTailsTime,1))) > random(0.0,1.0,{})"\n'.format(float(seed)))
    f.write('\n')
    f.close()


    f=open(Reaction_dir+'Map_Depolymerisation2.txt','w')
    f.write('#Depolimerisation1 3-mer\n')
    f.write('\n')
    f.write('3 equivalences\n')
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('custom "(1.0-exp(-rxndiffIvan(v_vTailsTime,1))) > random(0.0,1.0,{})"\n'.format(float(seed)))
    f.write('\n')
    f.close()

    f=open(Reaction_dir+'Map_Depolymerisation3.txt','w')
    f.write('#Depolimerisation1 dimer\n')
    f.write('\n')
    f.write('2 equivalences\n')
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('custom "(1.0-exp(-rxndiffIvan(v_vTailsTime,1))) > random(0.0,1.0,{})"\n'.format(float(seed)))
    f.write('\n')
    f.close()
    

    f=open(Reaction_dir+'Map_Polymerisation0.txt','w')
    f.write('#Poymerisation Nucleation\n')
    f.write('\n')
    f.write('2 equivalences\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('\n')
    f.close()

    f=open(Reaction_dir+'Map_Polymerisation1.txt','w')
    f.write('#Poymerisation Dimer+1\n')
    f.write('\n')
    f.write('3 equivalences\n')
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('angle 1 2 3 150 210\n')
    f.close()

    f=open(Reaction_dir+'Map_Polymerisation2.txt','w')
    f.write('#Poymerisation2 3-mer+1\n')
    f.write('\n')
    f.write('4 equivalences\n')
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('4 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('angle 1 2 3 150 210\n')
    f.close()
    
    f=open(Reaction_dir+'Map_Polymerisation3.txt','w')
    f.write('#Poymerisation3 4-mer+1\n')
    f.write('\n')
    f.write('4 equivalences\n')
    f.write('1 edgeIDs\n') 
    f.write('1 constraints\n')
    f.write('\n')
    f.write('InitiatorIDs\n')
    f.write('\n')
    f.write('1\n')
    f.write('2\n')
    f.write('\n')
    f.write('\n')
    f.write('EdgeIDs\n')
    f.write('\n')
    f.write('4\n')
    f.write('\n')
    f.write('\n')
    f.write('Equivalences\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('4 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Constraints\n')
    f.write('\n')
    f.write('angle 1 2 3 150 210\n')
    f.close()
    
    f=open(Reaction_dir+'Post_Depolymerisation0.txt','w')
    f.write('#Post Depol0 \n')
    f.write('\n')
    f.write('4 atoms\n')
    f.write('2 bonds\n')
    f.write('1 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 3\n')
    f.write('3 2\n')
    f.write('4 2\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.write('2 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 2 3 4\n')
    f.write('\n')
    f.close()

    f=open(Reaction_dir+'Post_Depolymerisation1.txt','w')
    f.write('#Post Depol1 \n')
    f.write('\n')
    f.write('4 atoms\n')
    f.write('2 bonds\n')
    f.write('1 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 3\n')
    f.write('3 2\n')
    f.write('4 1\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.write('2 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 2 3 4\n')
    f.write('\n')
    f.close()


    f=open(Reaction_dir+'Post_Depolymerisation2.txt','w')
    f.write('#Post Depol2 \n')
    f.write('3 atoms\n')
    f.write('1 bonds\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 3\n')
    f.write('3 1\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.close()


    f=open(Reaction_dir+'Post_Depolymerisation3.txt','w')
    f.write('#Post Depol3 \n')
    f.write('\n')
    f.write('2 atoms\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 4\n')
    f.close()



    f=open(Reaction_dir+'Post_Polymerisation1.txt','w')
    f.write('#Post Pol1 \n')
    f.write('\n')
    f.write('3 atoms\n')
    f.write('2 bonds\n')
    f.write('1 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.write('2 1 1 2\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 1 2 3\n')
    f.write('\n')
    f.close()

    f=open(Reaction_dir+'Post_Polymerisation2.txt','w')
    f.write('#Post Pol1 \n')
    f.write('4 atoms\n')
    f.write('3 bonds\n')
    f.write('2 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 2\n')
    f.write('4 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 1 2\n')
    f.write('2 1 2 3\n')
    f.write('3 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 1 2 3\n')
    f.write('2 1 2 3 4\n')
    f.write('\n')
    f.close()

    f=open(Reaction_dir+'Post_Polymerisation3.txt','w')
    f.write('#Post Pol3 \n')
    f.write('4 atoms\n')
    f.write('3 bonds\n')
    f.write('2 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 2\n')
    f.write('3 2\n')
    f.write('4 2\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 1 2\n')
    f.write('2 1 2 3\n')
    f.write('3 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 1 2 3\n')
    f.write('2 1 2 3 4\n')
    f.write('\n')
    f.close()

    f=open(Reaction_dir+'Pre_Depolymerisation0.txt','w')
    f.write('# Pre Depol0 \n')
    f.write('\n')
    f.write('4 atoms\n')
    f.write('3 bonds\n')
    f.write('2 angles\n')
    f.write('1 fragments\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 3\n')
    f.write('2 2\n')
    f.write('3 2\n')
    f.write('4 2\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 1 2\n')
    f.write('2 1 2 3\n')
    f.write('3 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 1 2 3\n')
    f.write('2 1 2 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Fragments\n')
    f.write('\n')
    f.write('1 1\n')
    f.close()

    f=open(Reaction_dir+'Pre_Depolymerisation1.txt','w')
    f.write('#Pre Depol1 \n')
    f.write('4 atoms\n')
    f.write('3 bonds\n')
    f.write('2 angles\n')
    f.write('1 fragments\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 3\n')
    f.write('2 2\n')
    f.write('3 2\n')
    f.write('4 1\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 1 2\n')
    f.write('2 1 2 3\n')
    f.write('3 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 1 2 3\n')
    f.write('2 1 2 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Fragments\n')
    f.write('\n')
    f.write('1 1\n')
    f.close()

    f=open(Reaction_dir+'Pre_Depolymerisation2.txt','w')
    f.write('#Pre Depol2 \n')
    f.write('3 atoms\n')
    f.write('2 bonds\n')
    f.write('1 angles\n')
    f.write('1 fragments\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 3\n')
    f.write('2 2\n')
    f.write('3 1\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 1 2\n')
    f.write('2 1 2 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 1 2 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Fragments\n')
    f.write('\n')
    f.write('1 1\n')
    f.close()    

    f=open(Reaction_dir+'Pre_Depolymerisation3.txt','w')
    f.write('#Pre Depol3 \n')
    f.write('2 atoms\n')
    f.write('1 bonds\n')
    f.write('1 fragments\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 1\n')
    f.write('2 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 1 2\n')
    f.write('\n')
    f.write('\n')
    f.write('Fragments\n')
    f.write('\n')
    f.write('1 1\n')
    f.close()    

    f=open(Reaction_dir+'Pre_Polymerisation1.txt','w')
    
    f.write('#Pre Pol1 \n')
    f.write('\n')
    f.write('3 atoms\n')
    f.write('1 bonds\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 1\n')
    f.write('3 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.close()    

    f=open(Reaction_dir+'Pre_Polymerisation2.txt','w')
    f.write('#Pre Pol2 \n')
    f.write('4 atoms\n')
    f.write('2 bonds\n')
    f.write('1 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 1\n')
    f.write('3 2\n')
    f.write('4 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.write('2 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 2 3 4\n')
    f.close()    
    
    f=open(Reaction_dir+'Pre_Polymerisation2.txt','w')
    f.write('#Pre Pol2 \n')
    f.write('4 atoms\n')
    f.write('2 bonds\n')
    f.write('1 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 1\n')
    f.write('3 2\n')
    f.write('4 3\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.write('2 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 2 3 4\n')
    f.close()

    f=open(Reaction_dir+'Pre_Polymerisation3.txt','w')
    f.write('#Pre Pol3 \n')
    f.write('4 atoms\n')
    f.write('2 bonds\n')
    f.write('1 angles\n')
    f.write('\n')
    f.write('\n')
    f.write('Types\n')
    f.write('\n')
    f.write('1 4\n')
    f.write('2 1\n')
    f.write('3 2\n')
    f.write('4 2\n')
    f.write('\n')
    f.write('\n')
    f.write('Bonds\n')
    f.write('\n')
    f.write('1 1 2 3\n')
    f.write('2 1 3 4\n')
    f.write('\n')
    f.write('\n')
    f.write('Angles\n')
    f.write('\n')
    f.write('1 1 2 3 4\n')
    f.close()    

    return 





def main_OneFilament(steps,Tau,mu,PBB,Box,Nsim,Mc_steps):
    
    # Atoms=int(300)
    # Fil_L=int(20)
    Angle_types=1
    Atom_types=4
    Bond_types=1

    Parent_dir='MC_One_Filament/Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}/'.format(Tau,mu,PBB,Box[1],Box[3])
    Reactions(Parent_dir,Nsim)
    Config_dir=Config_file_OneFilament(Parent_dir,Tau,mu,PBB,Box,Nsim,Angle_types,Atom_types,Bond_types)
    Input_file_OneFilament(Parent_dir,steps,Tau,mu,PBB,Box,Config_dir,Nsim,Mc_steps)




def main(Tau,mu,PBB,Box,Nsim):
    
    # Atoms=int(300)
    # Fil_L=int(20)
    Angle_types=1
    Atom_types=4
    Bond_types=1
    Parent_dir='./MC_Filaments_Tau_{}_mu_{}_PBB_{}_Lx_{}_Ly_{}_Nsim_{}/'.format(Tau,mu,PBB,Box[1],Box[3],Nsim)
    os.makedirs(Parent_dir,exist_ok=True)



    Config_dir=Config_file(Parent_dir,Tau,mu,PBB,Box,Nsim,Angle_types,Atom_types,Bond_types)
    Input_file(Parent_dir,Tau,mu,PBB,Box,Config_dir,Nsim)
    
    
main_OneFilament(steps,Tau,mu,PBB,Box,Nsim,Mc_steps)
print('Did this part jeje')


# for Nsim in range(Nsim_ini,Nsim_fin):
#     for Tau in Taus:
#         for PBB in PBBs:
#             for mu in mus:
#                 print('NOt this jeje')
            # main_Filament(float(Tau),mu,Box,Nsim)
                # main_OneFilament(float(Tau),mu,PBB,Box,Nsim)
